import {defineConfig} from "vite";
import path from "path";
const config = defineConfig({
    build: {
        lib: {
            entry: path.resolve(__dirname, 'index.ts'),
            name: "vite-build-helper",
            formats: ['es','umd','cjs' ], // adding 'umd' requires globals set to every external module
            fileName: (format) => `vite-build-helper.${format}.js`,
        },
        emptyOutDir: false, // to retain the types folder generated by tsc,
        rollupOptions:{
            external:['vite']
        }
    },
});


export default config
